services:
  app:
    build:
      context: .
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - sandbox

  sandbox:
    image: gcc:latest
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/sandbox
    security_opt:
      - seccomp=unconfined
